name: XcodeGenSample
packages:
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    majorVersion: 6.0.0
  #SwiftPM:
  #  url: https://github.com/apple/swift-package-manager
  # branch: swift-5.0-branch

schemes:
  XcodeGenSample-UAT:
    build:
      targets:
        XcodeGenSample: all
    run:
      config: UAT-Debug
      commandLineArguments:
        -FIRDebugDisabled: NO
        -FIRDebugEnable: YES
    archive:
      config: UAT-Release
  XcodeGenSample-PROD:
    build:
      targets:
        XcodeGenSample: all
    run:
      config: PROD-Debug
    archive:
      config: PROD-Release
configs:
  UAT-Debug: debug
  UAT-Release: release
  PROD-Debug: debug
  PROD-Release: release
configFiles:
  UAT-Debug: XcodeGenSample/Config/UAT-Debug.xcconfig
  UAT-Release: XcodeGenSample/Config/UAT-Release.xcconfig
  PROD-Debug: XcodeGenSample/Config/PROD-Debug.xcconfig
  PROD-Release: XcodeGenSample/Config/PROD-Release.xcconfig
settings:
  CODE_SIGN_STYLE: Manual
  ENABLE_BITCODE: false

options:
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 12.0
  xcodeVersion: 14.0

targets:
  XcodeGenSample:
    dependencies:
      - package: Kingfisher
    info:
      path: XcodeGenSample/Config/Info.plist
      properties:
        CFBundleDevelopmentRegion: zh-hant
        UIUserInterfaceStyle: Light
        CFBundleDisplayName: $(CFG_APP_NAME)
        CFBundleShortVersionString: $(CFG_APP_VERSION)
        CFBundleVersion: $(CFG_APP_BUILD)
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        NSCameraUsageDescription: Enable camera access to capture photos and videos.
        NSPhotoLibraryAddUsageDescription: Allow this app to save photos and videos to your photo library.
        NSPhotoLibraryUsageDescription: Access to your photo library is required to select and share photos and videos within the app.
        NSLocationWhenInUseUsageDescription: Allow this app to access your location while in use to provide relevant location-based features.
        NSMicrophoneUsageDescription: Grant access to your microphone to enable audio recording and use voice features within the app.
        NSSpeechRecognitionUsageDescription: Enable speech recognition to use voice commands and dictation within the app.
        CfgMode: $(CFG_MODE)
        ITSAppUsesNonExemptEncryption: false
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIBackgroundModes: [location, remote-notification]
        NSAppTransportSecurity:
          NSExceptionDomains:
            your-app-ats.exception.domain.com.tw:
              NSExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
    type: application
    platform: iOS
    deploymentTarget: "12.0"

    preBuildScripts:
      - path: "/bin/sh"
        script: '"$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/R.generated.swift"'
        name: Generate R.swift
        basedOnDependencyAnalysis: false
        outputFiles:
          - $SRCROOT/R.generated.swift

    settings:
      base:
        INFOPLIST_FILE: XcodeGenSample/Config/Info.plist
        PRODUCT_NAME: XcodeGenSample
        TARGETED_DEVICE_FAMILY: [1, 2] #1 is iPhone, 2 is iPad
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_OBJC_BRIDGING_HEADER: XcodeGenSample/Resources/XcodeGenSample-Bridging-Header.h
        CODE_SIGN_IDENTITY: $(CFG_CODE_SIGN_IDENTITY)
        CODE_SIGN_ENTITLEMENTS: $(CFG_CODE_SIGN_ENTITLEMENTS)
        PRODUCT_BUNDLE_IDENTIFIER: $(CFG_PRODUCT_BUNDLE_IDENTIFIER)
        PROVISIONING_PROFILE_SPECIFIER: $(CFG_PROVISIONING_PROFILE_SPECIFIER)
        DEVELOPMENT_TEAM: $(CFG_DEVELOPMENT_TEAM)
    sources:
      - path: XcodeGenSample
        name: XcodeGenSample
        type: group
      - path: ./R.generated.swift
