name: xcgendemo
configs:
  DEBUG: debug
  STAGING: release
  RELEASE: release
configFiles:
  DEBUG: xcgendemo/configs/debug.xcconfig
  STAGING: xcgendemo/configs/staging.xcconfig
  RELEASE: xcgendemo/configs/release.xcconfig
settings:
  CODE_SIGN_STYLE: Manual
  # CODE_SIGN_IDENTITY: sign.identity
  DEVELOPMENT_TEAM: dev.team
  FRAMEWORK_SEARCH_PATHS: Frameworks/
  #CODE_SIGN_ENTITLEMENTS:
  #FRAMEWORK_SEARCH_PATHS: Frameworks
options:
  createIntermediateGroups: true
  #bundleIdPrefix: tw.idv.pokeduck
  deploymentTarget:
    iOS: 12.0
  xcodeVersion: 12.3
  #findCarthageFrameworks: false
  #carthageBuildPath: ../FrameworksA/
  #carthageExecutablePath: mint run Carthage/Carthage
  #carthageBuildPath: Frameworks

targets:
  XCGenDemo:
    #info:
    #  path: xcgendemo/misc/info.plist
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    #dependencies:
    #- carthage: RxSwift
    #CARTHAGE_BUILD_PATH: Frameworks
    # - framework: Frameworks/RxSwift.framework
    # - framework: Frameworks/RxCocoa.framework
    # - framework: Frameworks/RxBlocking.framework
    # - framework: Frameworks/RxRelay.framework
    # - framework: Frameworks/RxTest.framework
    # - framework: Frameworks/Differentiator.framework
    # - framework: Frameworks/RxDataSources.framework
    # - framework: Frameworks/SnapKit.framework

    #configFiles:
    #  DEBUG: PracticeUI/configs/debug.xcconfig
    # STAGING: PracticeUI/configs/staging.xcconfig
    #  RELEASE: PracticeUI/configs/release.xcconfig
    preBuildScripts:
      - script: swiftformat .
    settings:
      base:
        PRODUCT_NAME: XCGenDemo
        CODE_SIGN_IDENTITY: ${CUSTOM_BUILD_SETTING}
        PRODUCT_BUNDLE_IDENTIFIER: ${CUSTOM_BUILD_SETTING}
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_OBJC_BRIDGING_HEADER: xcgendemo/misc/XCGenDemo-Bridging-Header.h
      configs:
        DEBUG:
          CUSTOM_BUILD_SETTING: debug.idv.pokeduck
        STAGING:
          CUSTOM_BUILD_SETTING: staging.idv.pokeduck
        RELEASE:
          CUSTOM_BUILD_SETTING: release.idv.pokeduck
    sources:
      - path: xcgendemo
