name: XcodeGenSample
schemes:
  XcodeGenSample-STAGING:
    build:
      targets:
        XcodeGenSample: all
    run:
      config: DEV
    archive:
      config: STAGING
  XcodeGenSample-PROD:
    build:
      targets:
        XcodeGenSample: all
    run:
      config: DEV
    archive:
      config: PROD
configs:
  DEV: debug
  STAGING: debug
  PROD: release
configFiles:
  DEV: XcodeGenSample/Config/dev.xcconfig
  STAGING: XcodeGenSample/Config/dev.xcconfig
  PROD: XcodeGenSample/Config/dev.xcconfig
settings:
  CODE_SIGN_STYLE: Manual
  ENABLE_BITCODE: false

options:
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 11.0
  xcodeVersion: 14.0

targets:
  XcodeGenSample:
    info:
      path: XcodeGenSample/Config/Info.plist
      properties:
        CFBundleDevelopmentRegion: zh-hant
        UIUserInterfaceStyle: Light
        CFBundleDisplayName: $(CFG_APP_NAME)
        CFBundleShortVersionString: $(CFG_APP_VERSION)
        CFBundleVersion: $(CFG_APP_BUILD)
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        NSCameraUsageDescription: 請給相機
        NSPhotoLibraryAddUsageDescription: 存相簿
        NSPhotoLibraryUsageDescription: 請給相簿
        NSLocationWhenInUseUsageDescription: 請給位置3Q
        NSMicrophoneUsageDescription: 請給麥克風
        NSSpeechRecognitionUsageDescription: 請支援語音辨識
        CfgMode: $(CFG_MODE)
        ITSAppUsesNonExemptEncryption: false
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIBackgroundModes: [location, remote-notification]
        NSAppTransportSecurity:
          NSExceptionDomains:
            leezen.stg.begonia-design.com.tw:
              NSExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
    type: application
    platform: iOS
    deploymentTarget: "11.0"

    preBuildScripts:
      - path: "/bin/sh"
        script: '"$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/R.generated.swift"'
        name: Generate R.swift
        basedOnDependencyAnalysis: false
        outputFiles:
          - $SRCROOT/R.generated.swift

    settings:
      base:
        INFOPLIST_FILE: XcodeGenSample/Config/Info.plist
        PRODUCT_NAME: XcodeGenSample
        TARGETED_DEVICE_FAMILY: [1, 2] #1 is iPhone, 2 is iPad
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_OBJC_BRIDGING_HEADER: XcodeGenSample/Resources/XcodeGenSample-Bridging-Header.h
      configs:
        DEV:
          CODE_SIGN_IDENTITY: "Apple Development: Your Cert Name(YOUR_TEAM_ID)"
          CODE_SIGN_ENTITLEMENTS: XcodeGenSample/Config/XcodeGenSample-Dev.entitlements
          PRODUCT_BUNDLE_IDENTIFIER: bundle.id.xcode.gen.sample.01
          PROVISIONING_PROFILE_SPECIFIER: your_provisioning_profile_name
          DEVELOPMENT_TEAM: YOUR_DEV_TEAM_ID
        STAGING:
          CODE_SIGN_IDENTITY: "Apple Distribution: YOUR_CERT_NAME (YOUR_TEAM_ID)"
          CODE_SIGN_ENTITLEMENTS: XcodeGenSample/Config/XcodeGenSample-Staging.entitlements
          PRODUCT_BUNDLE_IDENTIFIER: bundle.id.xcode.gen.sample.01
          PROVISIONING_PROFILE_SPECIFIER: your_staging_provisioning_profile_name
          DEVELOPMENT_TEAM: YOUR_DEV_TEAM_ID
        PROD:
          CODE_SIGN_IDENTITY: "Apple Distribution: YOUR_CERT_NAME (YOUR_TEAM_ID)"
          CODE_SIGN_ENTITLEMENTS: XcodeGenSample/Config/XcodeGenSample-Prod.entitlements
          PRODUCT_BUNDLE_IDENTIFIER: bundle.id.xcode.gen.sample.01
          PROVISIONING_PROFILE_SPECIFIER: your_prod_provisioning_profile_name
          DEVELOPMENT_TEAM: YOUR_DEV_TEAM_ID
    sources:
      - path: XcodeGenSample
        name: XcodeGenSample
        type: group
      - path: ./R.generated.swift
